--------------------------------------------------------
--  File created - Tuesday-December-26-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "USER20"."CUSTOMER" 
   (	"SSN" NUMBER(*,0), 
	"CUSTOMER_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LNAME" VARCHAR2(255 BYTE), 
	"FNAME" VARCHAR2(255 BYTE), 
	"DOB" DATE, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"CUSTOMERTYPE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER02" ;
REM INSERTING into USER20.CUSTOMER
SET DEFINE OFF;
Insert into USER20.CUSTOMER (SSN,CUSTOMER_ID,LNAME,FNAME,DOB,ADDRESS,CUSTOMERTYPE) values (222222222,2,'Johnson','Alice',to_date('15-MAY-85','DD-MON-RR'),'456 Oak Ave','Business');
Insert into USER20.CUSTOMER (SSN,CUSTOMER_ID,LNAME,FNAME,DOB,ADDRESS,CUSTOMERTYPE) values (333333333,3,'Williams','Robert',to_date('20-NOV-78','DD-MON-RR'),'789 Pine Blvd','Personal');
Insert into USER20.CUSTOMER (SSN,CUSTOMER_ID,LNAME,FNAME,DOB,ADDRESS,CUSTOMERTYPE) values (444444444,4,'Davis','Emily',to_date('10-MAR-95','DD-MON-RR'),'101 Elm St','Joint');
Insert into USER20.CUSTOMER (SSN,CUSTOMER_ID,LNAME,FNAME,DOB,ADDRESS,CUSTOMERTYPE) values (555555555,5,'Miller','Michael',to_date('25-SEP-80','DD-MON-RR'),'202 Cedar Ln','Business');
Insert into USER20.CUSTOMER (SSN,CUSTOMER_ID,LNAME,FNAME,DOB,ADDRESS,CUSTOMERTYPE) values (123456788,6,'Doe','Jane',to_date('10-MAY-80','DD-MON-RR'),'456 Birch St','Joint');
--------------------------------------------------------
--  DDL for Index SYS_C0016565
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER20"."SYS_C0016565" ON "USER20"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER02" ;
--------------------------------------------------------
--  DDL for Index SYS_C0016566
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER20"."SYS_C0016566" ON "USER20"."CUSTOMER" ("SSN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER02" ;
--------------------------------------------------------
--  DDL for Trigger ADDRESSCHANGETRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "USER20"."ADDRESSCHANGETRIGGER" 
BEFORE UPDATE ON Customer
FOR EACH ROW
BEGIN
    -- Check if the address is being updated
    IF :OLD.Address IS NOT NULL AND :NEW.Address IS NOT NULL AND :OLD.Address <> :NEW.Address THEN
        -- Insert a record into the log table
        INSERT INTO AddressChangeLog (CustomerID, OldAddress, NewAddress, ChangeDate, UserID)
        VALUES (:NEW.Customer_id, :OLD.Address, :NEW.Address, CURRENT_TIMESTAMP, USER);
    END IF;
END;

/
ALTER TRIGGER "USER20"."ADDRESSCHANGETRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "USER20"."CUSTOMER" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "USER20"."CUSTOMER" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "USER20"."CUSTOMER" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "USER20"."CUSTOMER" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "USER20"."CUSTOMER" ADD PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER02"  ENABLE;
  ALTER TABLE "USER20"."CUSTOMER" ADD UNIQUE ("SSN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER02"  ENABLE;
  ALTER TABLE "USER20"."CUSTOMER" ADD CONSTRAINT "CHECKCUSTOMERTYPE" CHECK (CustomerType IN ('Business', 'Personal', 'Joint')) ENABLE;
